const booksData = [
    {
      id: 1,
      title: "Math",
      price: 15.99,
      location: "Wembely",
      availability: 6,
      cartItem: 0,
      icon: "Icons/icons8-math-book-100.png",
    },
    {
      id: 2,
      title: "Music",
      price: 12.99,
      location: "Watford",
      availability: 5,
      cartItem: 0,
      icon: "Icons/icons8-music-book-100.png",
    },
    {
      id: 3,
      title: "Art",
      price: 10.49,
      location: "Aldershot",
      availability: 9,
      cartItem: 0,
      icon: "Icons/icons8-art-book-100.png",
    },
    {
      id: 4,
      title: "Sport",
      price: 19.99,
      location: "Brentford",
      availability: 7,
      cartItem: 0,
      icon: "Icons/icons8-sport-book-100.png",
    },
    {
      id: 5,
      title: "Physics",
      price: 8.99,
      location: "Camden Town",
      availability: 6,
      cartItem: 0,
      icon: "Icons/icons8-physics-book-100.png",
    },
    {
      id: 6,
      title: "Health",
      price: 15.99,
      location: "Euston",
      availability: 5,
      cartItem: 0,
      icon: "Icons/icons8-health-book-100.png",
    },
    {
      id: 7,
      title: "English",
      price: 12.99,
      location: "Harrow",
      availability: 10,
      cartItem: 0,
      icon: "Icons/icons8-english-book-100.png",
    },
    {
      id: 8,
      title: "Law",
      price: 10.49,
      location: "Central london",
      availability: 8,
      cartItem: 0,
      icon: "Icons/icons8-law-book-100.png",
    },
    {
      id: 9,
      title: "History",
      price: 19.99,
      location: "Arsenal",
      availability: 7,
      cartItem: 0,
      icon: "Icons/icons8-history-book-100.png",
    },
    {
      id: 10,
      title: "Geography",
      price: 9.99,
      location: "Manchester",
      availability: 9,
      cartItem: 0,
      icon: "Icons/icons8-geography-book-100.png",
    },
    {
      id: 11,
      title: "Buniness",
      price: 7.99,
      location: "Liverpool",
      availability: 6,
      cartItem: 0,
      icon: "Icons/icons8-business-book-100.png",
    },
    {
      id: 12,
      title: "Coding",
      price: 9.99,
      location: "Ealing",
      availability: 11,
      cartItem: 0,
      icon: "Icons/icons8-coding-book-100.png",
    },
  ];
  
  export default booksData;
  

  